import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import '../../assets/styles/globals.css';
import { LangContextProvider } from '@/contexts/LangContext';
import { LangType } from '@/lib/types/LangType';
import { getDictionary } from './dictionaries';
import Footer from '@/components/layout/Footer';

// const lato = Lato({
//   variable: '--font-lato',
//   subsets: ['latin'],
//   weight: '700',
// });

export const metadata: Metadata = {
  title: 'Car Market',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <Footer />
    </>
  );
}
